export const HUMANRAIL_PROGRAM_IDS = {
  HUMAN_REGISTRY: "GB35h1zNh8WK5c72yVXu6gk6U7eUMFiTTymrXk2dfHHo",
  AGENT_REGISTRY: "GLrs6qS2LLwKXZZuZXLFCaVyxkjBovbS2hM9PA4ezdhQ",
  DELEGATION: "DiNpgESa1iYxKkqmpCu8ULaXEmhqvD33ADGaaH3qP7XT",
  HUMAN_PAY: "HpMrfeC5gJZdywnUQS4WEvsUs6edyjrEmLuYEF1W3qF9",
  DATA_BLINK: "GYUeSsQfLYrYc5H27XdrssX5WgU4rNfkLGBnsksQcFpX",
  DOCUMENT_REGISTRY: "8uyGoBf7f9N2ChmaJrnVQ4sNRFtnRL4vp5Gi35MQ6Q28",
  RECEIPTS: "EFjLqSdPv45PmdhUwaFGRwCfENo58fRCtwTvqnQd8ZwM",
  DWALLET_GUARD: "Bzxgvxp9rZt2qeY7UNnvic9jHQdVFMw7mWzXvjuwLnT2",
} as const;

export const HUMANRAIL_GUARD_PROGRAM_ID =
  HUMANRAIL_PROGRAM_IDS.DWALLET_GUARD;
