import { Connection, PublicKey } from '@solana/web3.js';
import { AnchorProvider, Program, Idl, setProvider } from '@coral-xyz/anchor';
import {
  HUMAN_REGISTRY_PROGRAM_ID,
  HUMAN_PAY_PROGRAM_ID,
  DATA_BLINK_PROGRAM_ID,
} from './constants';

// IDL imports - these would be generated by Anchor build
// For now, we use placeholder types
import type { HumanRegistry } from './idl/human_registry';
import type { HumanPay } from './idl/human_pay';
import type { DataBlink } from './idl/data_blink';

export interface HumanRailClientConfig {
  connection: Connection;
  provider: AnchorProvider;
  registryProgramId?: PublicKey;
  payProgramId?: PublicKey;
  blinkProgramId?: PublicKey;
}

export class HumanRailClient {
  readonly connection: Connection;
  readonly provider: AnchorProvider;
  readonly registryProgramId: PublicKey;
  readonly payProgramId: PublicKey;
  readonly blinkProgramId: PublicKey;

  // Programs - lazily initialized
  private _registryProgram?: Program<HumanRegistry>;
  private _payProgram?: Program<HumanPay>;
  private _blinkProgram?: Program<DataBlink>;

  constructor(config: HumanRailClientConfig) {
    this.connection = config.connection;
    this.provider = config.provider;
    this.registryProgramId = config.registryProgramId ?? HUMAN_REGISTRY_PROGRAM_ID;
    this.payProgramId = config.payProgramId ?? HUMAN_PAY_PROGRAM_ID;
    this.blinkProgramId = config.blinkProgramId ?? DATA_BLINK_PROGRAM_ID;

    setProvider(this.provider);
  }

  /**
   * Create a client from a connection and wallet
   */
  static fromConnection(
    connection: Connection,
    wallet: AnchorProvider['wallet']
  ): HumanRailClient {
    const provider = new AnchorProvider(connection, wallet, {
      commitment: 'confirmed',
    });

    return new HumanRailClient({
      connection,
      provider,
    });
  }

  /**
   * Get the human registry program instance
   */
  get registryProgram(): Program<HumanRegistry> {
    if (!this._registryProgram) {
      // In a real implementation, this would load the IDL
      // For now, we throw an error indicating IDL needs to be loaded
      throw new Error(
        'Registry program not initialized. Load IDL with loadIdl() first.'
      );
    }
    return this._registryProgram;
  }

  /**
   * Get the human pay program instance
   */
  get payProgram(): Program<HumanPay> {
    if (!this._payProgram) {
      throw new Error(
        'Pay program not initialized. Load IDL with loadIdl() first.'
      );
    }
    return this._payProgram;
  }

  /**
   * Get the data blink program instance
   */
  get blinkProgram(): Program<DataBlink> {
    if (!this._blinkProgram) {
      throw new Error(
        'Blink program not initialized. Load IDL with loadIdl() first.'
      );
    }
    return this._blinkProgram;
  }

  /**
   * Load IDLs for all programs
   */
  async loadIdl(idls: {
    registry?: Idl;
    pay?: Idl;
    blink?: Idl;
  }): Promise<void> {
    if (idls.registry) {
      this._registryProgram = new Program(
        idls.registry,
        this.provider
      ) as unknown as Program<HumanRegistry>;
    }

    if (idls.pay) {
      this._payProgram = new Program(
        idls.pay,
        this.provider
      ) as unknown as Program<HumanPay>;
    }

    if (idls.blink) {
      this._blinkProgram = new Program(
        idls.blink,
        this.provider
      ) as unknown as Program<DataBlink>;
    }
  }

  /**
   * Get the wallet public key
   */
  get wallet(): PublicKey {
    return this.provider.wallet.publicKey;
  }
}
