export enum HumanRailErrorCode {
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
  AGENT_SUSPENDED = "AGENT_SUSPENDED",
  AGENT_REVOKED = "AGENT_REVOKED",
  AGENT_FROZEN = "AGENT_FROZEN",
  NO_CAPABILITY = "NO_CAPABILITY",
  CAPABILITY_EXPIRED = "CAPABILITY_EXPIRED",
  PER_TX_LIMIT_EXCEEDED = "PER_TX_LIMIT_EXCEEDED",
  DAILY_LIMIT_EXCEEDED = "DAILY_LIMIT_EXCEEDED",
  TOTAL_LIMIT_EXCEEDED = "TOTAL_LIMIT_EXCEEDED",
  PROGRAM_NOT_ALLOWED = "PROGRAM_NOT_ALLOWED",
  HUMAN_PROFILE_NOT_FOUND = "HUMAN_PROFILE_NOT_FOUND",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  RPC_ERROR = "RPC_ERROR",
  DOCUMENT_NOT_REGISTERED = "DOCUMENT_NOT_REGISTERED",
}

export class HumanRailError extends Error {
  constructor(
    message: string,
    public code: HumanRailErrorCode,
    public cause?: Error
  ) {
    super(message);
    this.name = "HumanRailError";
  }
}
