[toolchain]
anchor_version = "1.0.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
humanrail_dwallet_guard = "Bzxgvxp9rZt2qeY7UNnvic9jHQdVFMw7mWzXvjuwLnT2"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo no anchor tests yet"

[hooks]
