[toolchain]
anchor_version = "1.0.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
humanrail_dwallet_guard = "G2emUcBmNbFAQfP4deV68ciq9rtYc6pr6iYCt16WdYaF"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo no anchor tests yet"

[hooks]
