// This file is auto-generated by Anchor build
// Run `anchor build` to regenerate

export type DataBlink = {
  version: '0.1.0';
  name: 'data_blink';
  instructions: [
    {
      name: 'createTask';
      accounts: [
        { name: 'task'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'rewardMint'; isMut: false; isSigner: false },
        { name: 'creatorTokenAccount'; isMut: true; isSigner: false },
        { name: 'creator'; isMut: true; isSigner: true },
        { name: 'tokenProgram'; isMut: false; isSigner: false },
        { name: 'systemProgram'; isMut: false; isSigner: false }
      ];
      args: [{ name: 'params'; type: { defined: 'CreateTaskParams' } }];
    },
    {
      name: 'closeTask';
      accounts: [
        { name: 'task'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'rewardMint'; isMut: false; isSigner: false },
        { name: 'creatorTokenAccount'; isMut: true; isSigner: false },
        { name: 'creator'; isMut: true; isSigner: true },
        { name: 'tokenProgram'; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: 'submitResponse';
      accounts: [
        { name: 'task'; isMut: true; isSigner: false },
        { name: 'response'; isMut: true; isSigner: false },
        { name: 'workerProfile'; isMut: false; isSigner: false },
        { name: 'worker'; isMut: true; isSigner: true },
        { name: 'humanRegistryProgram'; isMut: false; isSigner: false },
        { name: 'systemProgram'; isMut: false; isSigner: false }
      ];
      args: [
        { name: 'choice'; type: 'u8' },
        { name: 'responseData'; type: { array: ['u8', 32] } }
      ];
    },
    {
      name: 'claimRewards';
      accounts: [
        { name: 'task'; isMut: false; isSigner: false },
        { name: 'response'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'rewardMint'; isMut: false; isSigner: false },
        { name: 'workerTokenAccount'; isMut: true; isSigner: false },
        { name: 'worker'; isMut: true; isSigner: true },
        { name: 'tokenProgram'; isMut: false; isSigner: false }
      ];
      args: [];
    }
  ];
  accounts: [
    {
      name: 'task';
      type: {
        kind: 'struct';
        fields: [
          { name: 'creator'; type: 'publicKey' },
          { name: 'rewardMint'; type: 'publicKey' },
          { name: 'rewardPerResponse'; type: 'u64' },
          { name: 'totalBudget'; type: 'u64' },
          { name: 'consumedBudget'; type: 'u64' },
          { name: 'humanRequirements'; type: 'u16' },
          { name: 'metadataUri'; type: 'string' },
          { name: 'isOpen'; type: 'bool' },
          { name: 'responseCount'; type: 'u32' },
          { name: 'maxResponses'; type: 'u32' },
          { name: 'allowMultipleResponses'; type: 'bool' },
          { name: 'createdAt'; type: 'i64' },
          { name: 'closedAt'; type: 'i64' },
          { name: 'vault'; type: 'publicKey' },
          { name: 'bump'; type: 'u8' },
          { name: 'vaultBump'; type: 'u8' }
        ];
      };
    },
    {
      name: 'taskResponse';
      type: {
        kind: 'struct';
        fields: [
          { name: 'task'; type: 'publicKey' },
          { name: 'worker'; type: 'publicKey' },
          { name: 'choice'; type: 'u8' },
          { name: 'responseData'; type: { array: ['u8', 32] } },
          { name: 'humanScoreAtSubmission'; type: 'u16' },
          { name: 'rewardAmount'; type: 'u64' },
          { name: 'isClaimed'; type: 'bool' },
          { name: 'submittedAt'; type: 'i64' },
          { name: 'claimedAt'; type: 'i64' },
          { name: 'bump'; type: 'u8' }
        ];
      };
    }
  ];
  types: [
    {
      name: 'CreateTaskParams';
      type: {
        kind: 'struct';
        fields: [
          { name: 'rewardPerResponse'; type: 'u64' },
          { name: 'totalBudget'; type: 'u64' },
          { name: 'humanRequirements'; type: 'u16' },
          { name: 'metadataUri'; type: 'string' },
          { name: 'maxResponses'; type: 'u32' },
          { name: 'allowMultipleResponses'; type: 'bool' }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: 'TaskNotOpen'; msg: 'Task is not open for responses' },
    { code: 6001; name: 'BudgetExhausted'; msg: 'Task budget is exhausted' },
    { code: 6002; name: 'InsufficientHumanScore'; msg: 'Worker does not meet minimum human score requirement' },
    { code: 6003; name: 'AlreadyResponded'; msg: 'Worker has already responded to this task' },
    { code: 6004; name: 'RewardAlreadyClaimed'; msg: 'Reward already claimed' }
  ];
};

export const IDL: DataBlink = {
  version: '0.1.0',
  name: 'data_blink',
  instructions: [],
  accounts: [],
  types: [],
  errors: [],
} as unknown as DataBlink;
