// This file is auto-generated by Anchor build
// Run `anchor build` to regenerate

export type HumanPay = {
  version: '0.1.0';
  name: 'human_pay';
  instructions: [
    {
      name: 'createConfidentialInvoice';
      accounts: [
        { name: 'invoice'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'mint'; isMut: false; isSigner: false },
        { name: 'merchant'; isMut: true; isSigner: true },
        { name: 'tokenProgram'; isMut: false; isSigner: false },
        { name: 'systemProgram'; isMut: false; isSigner: false }
      ];
      args: [{ name: 'params'; type: { defined: 'CreateInvoiceParams' } }];
    },
    {
      name: 'payConfidentialInvoice';
      accounts: [
        { name: 'invoice'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'mint'; isMut: false; isSigner: false },
        { name: 'payerProfile'; isMut: false; isSigner: false },
        { name: 'payerTokenAccount'; isMut: true; isSigner: false },
        { name: 'payer'; isMut: true; isSigner: true },
        { name: 'humanRegistryProgram'; isMut: false; isSigner: false },
        { name: 'tokenProgram'; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: 'cancelInvoice';
      accounts: [
        { name: 'invoice'; isMut: true; isSigner: false },
        { name: 'merchant'; isMut: false; isSigner: true }
      ];
      args: [];
    },
    {
      name: 'withdrawInvoice';
      accounts: [
        { name: 'invoice'; isMut: true; isSigner: false },
        { name: 'vault'; isMut: true; isSigner: false },
        { name: 'mint'; isMut: false; isSigner: false },
        { name: 'merchantTokenAccount'; isMut: true; isSigner: false },
        { name: 'merchant'; isMut: true; isSigner: true },
        { name: 'tokenProgram'; isMut: false; isSigner: false }
      ];
      args: [];
    }
  ];
  accounts: [
    {
      name: 'confidentialInvoice';
      type: {
        kind: 'struct';
        fields: [
          { name: 'merchant'; type: 'publicKey' },
          { name: 'payer'; type: 'publicKey' },
          { name: 'amount'; type: 'u64' },
          { name: 'mint'; type: 'publicKey' },
          { name: 'humanRequirements'; type: 'u16' },
          { name: 'status'; type: { defined: 'InvoiceStatus' } },
          { name: 'createdAt'; type: 'i64' },
          { name: 'expiresAt'; type: 'i64' },
          { name: 'paidAt'; type: 'i64' },
          { name: 'memo'; type: { array: ['u8', 32] } },
          { name: 'vault'; type: 'publicKey' },
          { name: 'bump'; type: 'u8' },
          { name: 'vaultBump'; type: 'u8' }
        ];
      };
    }
  ];
  types: [
    {
      name: 'CreateInvoiceParams';
      type: {
        kind: 'struct';
        fields: [
          { name: 'amount'; type: 'u64' },
          { name: 'humanRequirements'; type: 'u16' },
          { name: 'expiresAt'; type: 'i64' },
          { name: 'memo'; type: { array: ['u8', 32] } }
        ];
      };
    },
    {
      name: 'InvoiceStatus';
      type: {
        kind: 'enum';
        variants: [
          { name: 'Open' },
          { name: 'Paid' },
          { name: 'Cancelled' },
          { name: 'Withdrawn' }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: 'InvoiceAlreadyPaid'; msg: 'Invoice has already been paid' },
    { code: 6001; name: 'InvoiceExpired'; msg: 'Invoice has expired' },
    { code: 6002; name: 'InsufficientHumanScore'; msg: 'Payer does not meet minimum human score requirement' }
  ];
};

export const IDL: HumanPay = {
  version: '0.1.0',
  name: 'human_pay',
  instructions: [],
  accounts: [],
  types: [],
  errors: [],
} as unknown as HumanPay;
