// This file is auto-generated by Anchor build
// Run `anchor build` to regenerate

import { Idl } from '@coral-xyz/anchor';

export type HumanRegistry = {
  version: '0.1.0';
  name: 'human_registry';
  instructions: [
    {
      name: 'initProfile';
      accounts: [
        { name: 'profile'; isMut: true; isSigner: false },
        { name: 'wallet'; isMut: true; isSigner: true },
        { name: 'systemProgram'; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: 'registerAttestation';
      accounts: [
        { name: 'profile'; isMut: true; isSigner: false },
        { name: 'wallet'; isMut: false; isSigner: true }
      ];
      args: [
        {
          name: 'attestation';
          type: {
            defined: 'AttestationInput';
          };
        }
      ];
    },
    {
      name: 'recomputeScore';
      accounts: [
        { name: 'profile'; isMut: true; isSigner: false },
        { name: 'wallet'; isMut: false; isSigner: true }
      ];
      args: [];
    },
    {
      name: 'assertUnique';
      accounts: [
        { name: 'profile'; isMut: false; isSigner: false },
        { name: 'wallet'; isMut: false; isSigner: false }
      ];
      args: [{ name: 'minScore'; type: 'u16' }];
    }
  ];
  accounts: [
    {
      name: 'humanProfile';
      type: {
        kind: 'struct';
        fields: [
          { name: 'wallet'; type: 'publicKey' },
          { name: 'humanScore'; type: 'u16' },
          { name: 'isUnique'; type: 'bool' },
          { name: 'attestationCount'; type: 'u8' },
          { name: 'attestations'; type: { array: [{ defined: 'AttestationRef' }, 8] } },
          { name: 'lastUpdated'; type: 'i64' },
          { name: 'bump'; type: 'u8' }
        ];
      };
    }
  ];
  types: [
    {
      name: 'AttestationInput';
      type: {
        kind: 'struct';
        fields: [
          { name: 'sourceId'; type: 'publicKey' },
          { name: 'payloadHash'; type: { array: ['u8', 32] } },
          { name: 'signature'; type: { option: { array: ['u8', 64] } } },
          { name: 'attestationType'; type: { defined: 'AttestationType' } }
        ];
      };
    },
    {
      name: 'AttestationRef';
      type: {
        kind: 'struct';
        fields: [
          { name: 'sourceId'; type: 'publicKey' },
          { name: 'payloadHash'; type: { array: ['u8', 32] } },
          { name: 'attestationType'; type: 'u8' },
          { name: 'scoreWeight'; type: 'u16' },
          { name: 'registeredAt'; type: 'i64' },
          { name: 'isActive'; type: 'bool' }
        ];
      };
    },
    {
      name: 'AttestationType';
      type: {
        kind: 'enum';
        variants: [
          { name: 'SAS' },
          { name: 'WorldId' },
          { name: 'Civic' },
          { name: 'GitcoinPassport' },
          { name: 'Custom' }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: 'ProfileAlreadyExists'; msg: 'Profile already exists for this wallet' },
    { code: 6001; name: 'MaxAttestationsReached'; msg: 'Maximum attestations reached for this profile' },
    { code: 6002; name: 'AttestationAlreadyRegistered'; msg: 'Attestation from this source already registered' },
    { code: 6003; name: 'InvalidAttestationSignature'; msg: 'Invalid attestation signature' },
    { code: 6004; name: 'InsufficientHumanScore'; msg: 'Profile does not meet minimum human score requirement' },
    { code: 6005; name: 'NotUniqueHuman'; msg: 'Profile is not marked as unique human' }
  ];
};

export const IDL: HumanRegistry = {
  version: '0.1.0',
  name: 'human_registry',
  instructions: [],
  accounts: [],
  types: [],
  errors: [],
} as unknown as HumanRegistry;
